### ISSUE TITLE
Mirror Eidola are always Zombies

### ISSUE THREAD

**Issue by Flugkiller** [Hellmonk/bloatcrawl2#41]
What the title says. No matter if I choose in the beginning of the game to be normal, zombie, mummy or vampire, it will always end up choosing Zombie. Have only tested this with the Meteorologist background.

**Comment by alexjurkiewicz** [comment]
A couple of species have fixed undeadness, including Mirror Eidola, so that part is working as intended.

But there are two bugs:

1. In console/tiles the undead game modifier is greyed out, but not in webtiles. (i'll open another ticket for this)
2. Mirror Eidola probably shouldn't be Zombies, since they can't chunk heal. I think the intention behind this was making them torment resistant. Probably they should become alive with innate rTorment.
